import type { SeedAttendee } from '../types';

export const MATCH_SEED_ATTENDEES: SeedAttendee[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Sarah Chen',
      headline: 'Senior Product Manager at Google',
      company: 'Google',
      location: 'San Francisco, CA',
      summary: 'Building AI-assisted product experiences for growth and retention.',
      pastCompanies: ['Meta', 'Atlassian'],
      universities: ['Stanford University'],
      skills: ['Product Strategy', 'Growth', 'A/B Testing', 'AI', 'SaaS'],
    },
    onboardingAnswers: {
      personalityTraits: ['Extrovert', 'High Adaptability', 'Conscientious', 'Agreeable', 'High Agreeableness / Positivity'],
      primaryGoal: 'Meeting technical co-founders',
      conversationStyle: 'High-level strategic vision',
      favoriteTopics: ['AI & ML', 'SaaS', 'Startups', 'Leadership', 'Data Science'],
    },
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'David Miller',
      headline: 'VC Partner at Sequoia',
      company: 'Sequoia Capital',
      location: 'Menlo Park, CA',
      summary: 'Investing in early-stage B2B SaaS and AI-first teams.',
      pastCompanies: ['Bessemer Venture Partners', 'Goldman Sachs'],
      universities: ['Harvard University'],
      skills: ['Venture Capital', 'Fundraising', 'SaaS', 'B2B', 'AI'],
    },
    onboardingAnswers: {
      personalityTraits: ['Extrovert', 'High Adaptability', 'Conscientious', 'Agreeable', 'High Agreeableness / Positivity'],
      primaryGoal: 'Active investor',
      conversationStyle: 'Quick & direct exchanges',
      favoriteTopics: ['Startups', 'SaaS', 'Finance', 'AI & ML', 'Leadership'],
    },
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Maya Singh',
      headline: 'Staff ML Engineer at Stripe',
      company: 'Stripe',
      location: 'Seattle, WA',
      summary: 'Scaling recommendation and fraud models in payments.',
      pastCompanies: ['PayPal', 'Amazon'],
      universities: ['University of Washington'],
      skills: ['Machine Learning', 'Python', 'Fraud Detection', 'Payments', 'Data Science'],
    },
    onboardingAnswers: {
      personalityTraits: ['Introvert', 'High Adaptability', 'Conscientious', 'Disagreeable', 'Realistic / Neuroticism'],
      primaryGoal: 'Meeting technical co-founders',
      conversationStyle: 'Deep technical dives',
      favoriteTopics: ['AI & ML', 'Data Science', 'Finance', 'Cybersecurity', 'SaaS'],
    },
  },
  {
    id: '4',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Alicia Gomez',
      headline: 'Design Director at Figma',
      company: 'Figma',
      location: 'New York, NY',
      summary: 'Crafting product systems for collaborative software teams.',
      pastCompanies: ['Airbnb', 'Adobe'],
      universities: ['Parsons School of Design'],
      skills: ['UX Design', 'Design Systems', 'User Research', 'Brand', 'Leadership'],
    },
    onboardingAnswers: {
      personalityTraits: ['Extrovert', 'High Adaptability', 'Openness to Experience', 'Agreeable', 'High Agreeableness / Positivity'],
      primaryGoal: 'Just networking casually',
      conversationStyle: 'Casual & friendly chats',
      favoriteTopics: ['Design', 'Product Design & UX', 'Leadership', 'Media', 'Education'],
    },
  },
  {
    id: '5',
    image: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Omar Farouk',
      headline: 'Founder & CTO at Delta Robotics',
      company: 'Delta Robotics',
      location: 'Austin, TX',
      summary: 'Building autonomous systems for industrial operations.',
      pastCompanies: ['Tesla', 'Siemens'],
      universities: ['Georgia Tech'],
      skills: ['Robotics', 'Embedded Systems', 'Computer Vision', 'C++', 'AI'],
    },
    onboardingAnswers: {
      personalityTraits: ['Introvert', 'High Neuroticism', 'Conscientious', 'Disagreeable', 'Realistic / Neuroticism'],
      primaryGoal: 'Technical co-founder',
      conversationStyle: 'Deep technical dives',
      favoriteTopics: ['AI & ML', 'Robotics', 'Startups', 'Hardware', 'Cybersecurity'],
    },
  },
  {
    id: '6',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Priyanka Das',
      headline: 'Head of Growth at Notion',
      company: 'Notion',
      location: 'Los Angeles, CA',
      summary: 'Driving product-led growth and community loops.',
      pastCompanies: ['HubSpot', 'Dropbox'],
      universities: ['UCLA'],
      skills: ['Growth', 'PLG', 'Marketing', 'Analytics', 'SaaS'],
    },
    onboardingAnswers: {
      personalityTraits: ['Extrovert', 'High Adaptability', 'Openness to Experience', 'Agreeable', 'High Agreeableness / Positivity'],
      primaryGoal: 'Exploring new job opportunities',
      conversationStyle: 'High-level strategic vision',
      favoriteTopics: ['Marketing', 'SaaS', 'Startups', 'Leadership', 'Media'],
    },
  },
  {
    id: '7',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Jonas Klein',
      headline: 'Principal Security Architect at Cloudflare',
      company: 'Cloudflare',
      location: 'Chicago, IL',
      summary: 'Securing distributed systems at internet scale.',
      pastCompanies: ['Cisco', 'Microsoft'],
      universities: ['ETH Zurich'],
      skills: ['Cybersecurity', 'Networking', 'Cloud', 'Threat Modeling', 'Zero Trust'],
    },
    onboardingAnswers: {
      personalityTraits: ['Introvert', 'High Adaptability', 'Conscientious', 'Disagreeable', 'Realistic / Neuroticism'],
      primaryGoal: 'Exploring new job opportunities',
      conversationStyle: 'Quick & direct exchanges',
      favoriteTopics: ['Cybersecurity', 'Cloud', 'Data Science', 'AI & ML', 'SaaS'],
    },
  },
  {
    id: '8',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Nadia Alvi',
      headline: 'Founder at ClimateGrid',
      company: 'ClimateGrid',
      location: 'Boston, MA',
      summary: 'Building climate analytics infrastructure for cities.',
      pastCompanies: ['Palantir', 'UNDP'],
      universities: ['MIT'],
      skills: ['Climate Tech', 'Data Analytics', 'Policy', 'Startups', 'AI'],
    },
    onboardingAnswers: {
      personalityTraits: ['Extrovert', 'High Adaptability', 'Openness to Experience', 'Agreeable', 'High Agreeableness / Positivity'],
      primaryGoal: 'Finding potential investors',
      conversationStyle: 'High-level strategic vision',
      favoriteTopics: ['Sustainability', 'Startups', 'Data Science', 'Social Impact', 'AI & ML'],
    },
  },
  {
    id: '9',
    image: 'https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Ethan Park',
      headline: 'Engineering Manager at Shopify',
      company: 'Shopify',
      location: 'Toronto, ON',
      summary: 'Leading commerce platform teams and backend reliability.',
      pastCompanies: ['Shopify', 'Twilio'],
      universities: ['University of Toronto'],
      skills: ['Backend', 'Distributed Systems', 'Leadership', 'SaaS', 'Payments'],
    },
    onboardingAnswers: {
      personalityTraits: ['Introvert', 'High Adaptability', 'Conscientious', 'Agreeable', 'Realistic / Neuroticism'],
      primaryGoal: 'Meeting technical co-founders',
      conversationStyle: 'Deep technical dives',
      favoriteTopics: ['SaaS', 'Startups', 'Leadership', 'AI & ML', 'Finance'],
    },
  },
  {
    id: '10',
    image: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?auto=format&fit=crop&w=400&q=80',
    linkedIn: {
      name: 'Leila Haddad',
      headline: 'Product Marketing Lead at OpenAI',
      company: 'OpenAI',
      location: 'San Francisco, CA',
      summary: 'Launching AI products with clear positioning and adoption strategy.',
      pastCompanies: ['Canva', 'Salesforce'],
      universities: ['UC Berkeley'],
      skills: ['Product Marketing', 'Messaging', 'AI', 'Go-to-Market', 'SaaS'],
    },
    onboardingAnswers: {
      personalityTraits: ['Extrovert', 'High Adaptability', 'Openness to Experience', 'Agreeable', 'High Agreeableness / Positivity'],
      primaryGoal: 'Just networking casually',
      conversationStyle: 'Casual & friendly chats',
      favoriteTopics: ['AI & ML', 'Marketing', 'Startups', 'Media', 'Leadership'],
    },
  },
];
